#!/bin/sh
### BEGIN INIT INFO
# Provides: ssserver
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Shadowsocks server daemon
# Description: Shadowsocks server
### END INIT INFO

case "$1" in
  start)
    ssserver -c /etc/shadowsocks.json -d start
  ;;
  stop)
    ssserver -d stop
  ;;
  restart)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: /etc/init.d/ssserver {start|stop|restart}"
    exit 1
  ;;
esac
exit 0